mqtt_ip: 127.0.0.1
mqtt_port: 1883
SN: 1D80F5FB02C08F4

ips:
- 127.0.0.1
port_num: COM4
baud_rate: 9600

t_begin: 0
t_end: 21
e_idx: 22
ac_row: 0
seq_type: 3
tsp_num: 6
ga_size: 10
ga_epoch: 90

num_heads: 2
gnn_dim: 16
lstm_dim: 32
num_nodes: 6
seq_len: 3
edge_start: 0,1,0,2,0,3,1,2,1,3,1,5,2,3,4,5,1,4,4,3,5,0
edge_end: 1,0,2,0,3,0,2,1,3,1,5,1,3,2,5,4,4,1,3,4,0,5

learning_rate: 0.001
batch_size: 30
epoch: 500

step_size: 20
step_gamma: 0.9
T_max: 100

tsp_res: 5,11,7,6,20,13
